### ISSUE TITLE
lesson on the branch (hangman).io

### ISSUE THREAD

**Issue by mphetens** [mphetens/mphetens.github.io#4]
https://github.com/mphetens/mphetens.github.io/issues/2#issue-2535297305
![1725649277599](https://github.com/user-attachments/assets/6cf0888d-277d-44e7-a545-632c2e6be860)
git status #2 #3 #1

**Comment by mphetens** [comment]
[https://mphetens.github.io](url)

**Comment by amethystens** [comment]
> https://github.com/mphetens/mphetens.github.io/issues/2#issue-2535297305
> ![1725649277599](https://github.com/user-attachments/assets/6cf0888d-277d-44e7-a545-632c2e6be860)
> git status #2 #3 #1

**Comment by amethystens** [comment]
> https://github.com/mphetens/mphetens.github.io/issues/2#issue-2535297305
> ![1725649277599](https://github.com/user-attachments/assets/6cf0888d-277d-44e7-a545-632c2e6be860)
> git status #2 #3 #1

**Comment by mphetens** [comment]
nie aktualne

**Comment by mphetens** [comment]
nie aktualne
