### ISSUE TITLE
https://mphetens.github.io

### ISSUE THREAD

**Issue by mphetens** [mphetens/mphetens.github.io#7]
mphetens.github.io

_Originally posted by @mphetens in https://github.com/mphetens/mphetens.github.io/issues/1#issuecomment-2359960505_

**Comment by amethystens** [comment]
!

**Comment by amethystens** [comment]
>               mphetens.github.io
> 
> _Originally posted by @mphetens in https://github.com/mphetens/mphetens.github.io/issues/1#issuecomment-2359960505_
>

**Comment by amethystens** [comment]
>               mphetens.github.io
> 
> _Originally posted by @mphetens in https://github.com/mphetens/mphetens.github.io/issues/1#issuecomment-2359960505_
>

**Comment by mphetens** [comment]
nie aktualne
